<!DOCTYPE html>
<html>
<head>

    <link rel="stylesheet" type="text/css" href="../css/G_Grungeruest.css">
    <title>Spacegame 9000</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class=“Boxen“>
            <div class="col-sm">
                <div class=“box b“></div>
            </div>

            <nav class="navbar navbar-expand-md">
                <a class="navbar-brand" href="#">Spacegame9000</a>
                <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse"
                        data-target="#main-navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="main-navigation">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Gold: <?php echo $_SESSION["User"]->getGold() ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Metall: <?php echo $_SESSION["User"]->getMetall() ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Energie: <?php echo $_SESSION["User"]->getEnergie() ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">(Anzahl Schiffe)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Spieler: <?php echo $_SESSION["User"]->getUsername() ?></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Platzhalter</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="row" id="Planeten-row">
            <div class="col-sm">
                Aktiver Planet: <?php echo $_SESSION["User"]
                    ->getStaat()->getPlanet()->getPlanetName() ?>
            </div>

            <div class="col-sm">
                Max_Buildings: <?php echo $_SESSION["User"]
                    ->getStaat()->getPlanet()->getMaxCountBuildings() ?>
            </div>
            <div class="col-sm">
                Current_Buildings_on_Planet: <?php echo $_SESSION["User"]
                    ->getStaat()->getPlanet()->getCurrCountBuildings() ?>
            </div>
            <div class="col-sm"></div>

        </div>
<div class="row">
    <?php echo $_SESSION["User"]->getStaat()->getPlanet()->showBuildings() ?>
</div>
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">
                <div class="Inhalt_main">
                    <h1>Hier soll das Spiel stattfinden</h1>
                    <p>Ja Moin ! </p>
                </div>
            </div>
            <div class="col-sm"></div>
        </div>
    </div>
</div>
</div>

</body>
</html>