<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">SpaceGame9000</a>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <form class="float-sm-right" method="post">
                <input class="btn btn-outline-success" name="NavbarLoginButton" type="submit" value="Login">
                <input class="btn btn-outline-success" name="NavbarSignUpButton" type="submit" value="Sign-Up">
            </form>
        </li>
        <ul class="nav-item">
            Hallo <?php echo $Username ?>
        </ul>
    </ul>
</nav>